/**
 * This stylesheet deliberately follows ui-trajectory's dimensions and states:
 * 32px toolbar, 20px toolbar actions, 30px ledger rows, split inspector,
 * semantic --dsw-* tokens, and the same hover/focus treatments.
 */
export const STYLES = String.raw`
[data-agent-replay="true"]{display:none}
/* Replay is a read-only full-height view. The active view is the only mounted
   conversation.view entry, so :has(.ar-root) scopes this to Replay and the
   composer returns as soon as the user switches back to Chat or Trajectory. */
[data-conversation-scroll]:has(.ar-root)>[data-composer-seat]{display:none}
.ar-root,.ar-root *{box-sizing:border-box}
.ar-root{display:flex;flex-direction:column;overflow:hidden;width:100%;height:100%;min-width:0;min-height:0;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);font-family:var(--dsw-font-family)}
.ar-toolbar{position:sticky;top:0;z-index:4;display:flex;align-items:center;width:100%;height:32px;flex:none;padding:0 6px;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1)}
.ar-toolbar-actions{display:flex;align-items:center;gap:2px;flex:none}
.ar-toolbar-button{display:inline-flex;align-items:center;height:20px;padding:0 7px;gap:4px;border:0;border-radius:3px;color:var(--dsw-alias-label-tertiary);background:transparent;cursor:pointer;font:var(--dsw-font-xxs-12)}
.ar-toolbar-button:hover,.ar-toolbar-button.active{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
.ar-toolbar-button:focus-visible{outline:1px solid var(--dsw-alias-state-business-primary);outline-offset:1px}
.ar-toolbar-button svg{width:12px;height:12px;flex:none}
.ar-search{display:flex;align-items:center;width:164px;min-width:84px;height:22px;margin-left:auto;padding:0 6px;gap:4px;border:1px solid var(--dsw-alias-border-l2);border-radius:4px;color:var(--dsw-alias-label-caption);background:var(--dsw-alias-bg-layer-2)}
.ar-search:hover{border-color:var(--dsw-alias-label-caption)}.ar-search:focus-within{border-color:var(--dsw-alias-state-business-primary);background:var(--dsw-alias-bg-layer-1)}
.ar-search svg{width:11px;height:11px;flex:none}.ar-search input{width:100%;min-width:0;padding:0;border:0;outline:0;color:var(--dsw-alias-label-primary);background:transparent;font:var(--dsw-font-xxs-12)}.ar-search input::placeholder{color:var(--dsw-alias-label-caption)}
.ar-status{display:flex;align-items:center;gap:5px;flex:none;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-status>i{width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-state-success-primary)}.ar-status>i.live{animation:ar-pulse 1.5s ease-in-out infinite}.ar-status>b{padding-left:8px;border-left:1px solid var(--dsw-alias-border-l2);font-weight:400;color:var(--dsw-alias-label-caption)}
.ar-summary{display:flex;align-items:center;height:50px;flex:none;padding:0 12px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-specific-sidebar-fill)}
.ar-metric{display:flex;align-items:baseline;gap:5px;min-width:82px;padding:0 12px;border-right:1px solid var(--dsw-alias-border-l2)}.ar-metric:first-child{padding-left:0}.ar-metric strong{font:var(--dsw-font-s-strong-14);font-variant-numeric:tabular-nums}.ar-metric span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-metric.danger strong{color:var(--dsw-alias-state-error-primary)}
.ar-event-map{display:flex;align-items:center;justify-content:flex-end;height:22px;flex:1;margin-left:12px;gap:2px;overflow:hidden}.ar-event-map i{display:block;width:3px;height:7px;flex:none;border-radius:1px;background:var(--dsw-alias-label-caption)}.ar-event-map i.user{height:12px;background:var(--dsw-alias-state-business-primary)}.ar-event-map i.assistant{height:16px;background:var(--dsw-alias-brand-primary-new-colorprimary-new-color)}.ar-event-map i.tool{height:10px;background:var(--dsw-alias-state-warn-label)}.ar-event-map i.error{height:16px;background:var(--dsw-alias-state-error-primary)}
.ar-workspace{display:flex;flex:1;width:100%;min-height:0;overflow:hidden;background:var(--dsw-alias-bg-layer-1)}
.ar-sidebar{display:flex;flex-direction:column;width:40%;min-width:300px;min-height:0;border-right:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1)}
.ar-filters{display:flex;align-items:center;height:30px;flex:none;padding:0 6px;gap:2px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-specific-sidebar-fill);overflow-x:auto}
.ar-filters button{display:inline-flex;align-items:center;height:20px;padding:0 5px;border:0;border-radius:3px;color:var(--dsw-alias-label-tertiary);background:transparent;cursor:pointer;font:var(--dsw-font-xxs-12);white-space:nowrap}.ar-filters button:hover,.ar-filters button.active{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
.ar-list{flex:1;min-height:0;overflow-y:auto}.ar-event{position:relative;display:grid;grid-template-columns:28px minmax(0,1fr) 44px;align-items:center;width:100%;height:44px;padding:0 8px;gap:4px;border:0;border-bottom:1px solid var(--dsw-alias-border-l1);outline:0;color:inherit;background:transparent;text-align:left;cursor:default;transition:background-color 120ms var(--ds-ease-in-out),opacity 120ms var(--ds-ease-in-out)}
.ar-event:hover{background:var(--dsw-alias-interactive-bg-hover)}.ar-event.active{background:var(--dsw-alias-interactive-bg-active)}.ar-event.active::before{position:absolute;top:0;bottom:0;left:0;width:3px;background:var(--dsw-alias-brand-primary-new-colorprimary-new-color);content:""}.ar-event.future{opacity:.24}.ar-event.played:not(.active){opacity:.62}
.ar-event-icon{display:flex;align-items:center;justify-content:center;width:20px;height:20px;color:var(--dsw-alias-label-secondary)}.ar-event-icon.assistant{color:var(--dsw-alias-brand-primary-new-colorprimary-new-color)}.ar-event-icon.tool{color:var(--dsw-alias-state-warn-label)}.ar-event-icon.error{color:var(--dsw-alias-state-error-primary)}.ar-icon-svg{width:13px;height:13px}
.ar-event-copy{display:flex;flex-direction:column;min-width:0}.ar-event-copy strong,.ar-event-copy span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ar-event-copy strong{font:var(--dsw-font-xs-13);font-weight:500}.ar-event-copy span{margin-top:1px;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-event-time{color:var(--dsw-alias-label-caption);font:var(--dsw-font-xxs-12);font-variant-numeric:tabular-nums;text-align:right}
.ar-older{display:flex;align-items:center;justify-content:center;width:100%;height:29px;border:0;border-bottom:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-1);cursor:pointer;font:var(--dsw-font-xxs-12)}.ar-older:hover:not(:disabled){color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.ar-older:disabled{cursor:default}
.ar-no-match{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;color:var(--dsw-alias-label-tertiary);text-align:center}.ar-no-match svg{width:16px;margin-bottom:8px}.ar-no-match strong{font:var(--dsw-font-xs-13)}.ar-no-match span{margin-top:4px;font:var(--dsw-font-xxs-12)}
.ar-player{display:flex;align-items:center;height:42px;flex:none;padding:0 6px;gap:6px;border-top:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1)}.ar-play,.ar-restart{display:inline-flex;align-items:center;height:24px;padding:0 6px;gap:4px;border:0;border-radius:3px;color:var(--dsw-alias-label-tertiary);background:transparent;cursor:pointer;font:var(--dsw-font-xxs-12)}.ar-play:hover,.ar-restart:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.ar-play svg,.ar-restart svg{width:12px;height:12px}.ar-restart{width:24px;justify-content:center}
.ar-progress{display:flex;align-items:center;flex:1;min-width:40px;gap:6px}.ar-progress>div{height:2px;flex:1;background:var(--dsw-alias-border-l2)}.ar-progress i{display:block;height:100%;background:var(--dsw-alias-state-business-primary);transition:width 120ms var(--ds-ease-in-out)}.ar-progress span{color:var(--dsw-alias-label-caption);font:var(--dsw-font-xxs-12);font-variant-numeric:tabular-nums;white-space:nowrap}.ar-player select{height:22px;padding:0 4px;border:1px solid var(--dsw-alias-border-l2);border-radius:4px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);font:var(--dsw-font-xxs-12)}
.ar-detail{flex:1;min-width:0;min-height:0;overflow-y:auto;background:var(--dsw-alias-bg-layer-1)}.ar-detail-head{display:grid;grid-template-columns:32px minmax(0,1fr) auto;align-items:start;padding:16px;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-specific-sidebar-fill)}.ar-detail-icon{display:flex;align-items:center;justify-content:center;width:24px;height:24px;color:var(--dsw-alias-label-secondary)}.ar-detail-icon.assistant{color:var(--dsw-alias-brand-primary-new-colorprimary-new-color)}.ar-detail-icon.tool{color:var(--dsw-alias-state-warn-label)}.ar-detail-icon.error{color:var(--dsw-alias-state-error-primary)}.ar-detail-icon svg{width:14px;height:14px}.ar-detail-head>div>span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-detail-head h2{margin:3px 0 0;font:var(--dsw-font-s-strong-14)}.ar-detail-head p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font:var(--dsw-font-xs-13);line-height:1.5}.ar-live-badge{display:flex;align-items:center;gap:4px;padding:2px 5px;border-radius:3px;color:var(--dsw-alias-state-success-primary);background:var(--dsw-alias-state-success-tertiary);font:var(--dsw-font-xxs-12)}.ar-live-badge i{width:5px;height:5px;border-radius:50%;background:currentColor}
.ar-facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));border-bottom:1px solid var(--dsw-alias-border-l2)}.ar-facts>div{padding:9px 12px;border-right:1px solid var(--dsw-alias-border-l2)}.ar-facts span,.ar-facts strong{display:block}.ar-facts span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-facts strong{margin-top:3px;font:var(--dsw-font-xs-13);font-weight:500;font-variant-numeric:tabular-nums}
.ar-content-card{margin:12px;border:1px solid var(--dsw-alias-border-l2);border-radius:4px;overflow:hidden}.ar-content-head{display:flex;align-items:center;justify-content:space-between;height:30px;padding:0 8px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-specific-sidebar-fill)}.ar-content-head>span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12);font-weight:500}.ar-content-head button{display:flex;align-items:center;height:20px;padding:0 5px;gap:4px;border:0;border-radius:3px;color:var(--dsw-alias-label-tertiary);background:transparent;cursor:pointer;font:var(--dsw-font-xxs-12)}.ar-content-head button:hover:not(:disabled){color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.ar-content-head button svg{width:11px}.ar-content-card pre{min-height:160px;max-height:52vh;margin:0;padding:12px;overflow:auto;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-markdown-code-block);white-space:pre-wrap;word-break:break-word;font:var(--dsw-font-markdown-code-block-small);line-height:1.6}.ar-truth-note{display:flex;align-items:center;margin:0 12px 12px;gap:5px;color:var(--dsw-alias-label-caption);font:var(--dsw-font-xxs-12)}.ar-truth-note svg{width:11px}.ar-select-hint{display:grid;place-items:center;height:100%;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xs-13)}
.ar-publish{width:100%;min-height:100%}.ar-publish-head{display:flex;align-items:flex-start;justify-content:space-between;padding:16px;border-bottom:1px solid var(--dsw-alias-border-l2);background:var(--dsw-specific-sidebar-fill)}.ar-publish-head>div>span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-publish-head h2{margin:3px 0 0;font:var(--dsw-font-s-strong-14)}.ar-publish-head p{max-width:560px;margin:4px 0 0;color:var(--dsw-alias-label-secondary);font:var(--dsw-font-xs-13);line-height:1.5}.ar-publish-head>svg{width:16px;color:var(--dsw-alias-label-tertiary)}
.ar-settings{border-bottom:1px solid var(--dsw-alias-border-l2)}.ar-settings label,.ar-setting-row{display:grid;grid-template-columns:150px minmax(0,1fr);align-items:center;min-height:44px;padding:6px 12px;border-bottom:1px solid var(--dsw-alias-border-l1)}.ar-settings label>span:first-child,.ar-setting-row>span{display:flex;align-items:center;gap:5px;color:var(--dsw-alias-label-secondary);font:var(--dsw-font-xs-13)}.ar-setting-row>span svg{width:13px}.ar-settings-input{width:100%}.ar-setting-row>div{display:flex;flex-direction:column}.ar-setting-row strong{font:var(--dsw-font-xs-13);font-weight:400}.ar-setting-row small{margin-top:2px;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}
.ar-share-preview{position:relative;margin:12px;padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:4px;background:var(--dsw-alias-bg-layer-3)}.ar-share-preview>span{color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xxs-12)}.ar-share-preview h3{margin:5px 0 0;font:var(--dsw-font-l-strong-16)}.ar-share-preview p{margin:6px 0 0;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xs-13)}.ar-export{margin:12px}
.ar-empty-root{align-items:center;justify-content:center;text-align:center}.ar-empty-mark{display:grid;place-items:center;width:32px;height:32px;color:var(--dsw-alias-label-tertiary)}.ar-empty-mark svg{width:18px}.ar-empty-root h2{margin:8px 0 0;font:var(--dsw-font-s-strong-14)}.ar-empty-root p{max-width:360px;margin:4px 20px 0;color:var(--dsw-alias-label-tertiary);font:var(--dsw-font-xs-13);line-height:1.5}
@keyframes ar-pulse{50%{opacity:.35}}@media(prefers-reduced-motion:reduce){.ar-status>i.live{animation:none}}@media(max-width:760px){.ar-status>b,.ar-metric:nth-child(2),.ar-metric:nth-child(3){display:none}.ar-sidebar{min-width:270px;width:42%}.ar-settings label,.ar-setting-row{grid-template-columns:110px minmax(0,1fr)}}@media(max-width:600px){.ar-status{display:none}.ar-workspace{overflow-y:auto;flex-direction:column}.ar-sidebar{width:100%;min-width:0;height:360px;flex:none;border-right:0;border-bottom:1px solid var(--dsw-alias-border-l2)}.ar-detail{overflow:visible}.ar-event-map{display:none}}
`
